### ISSUE TITLE
Where do I put config values for a bundle being installed using the "old" way?

### ISSUE THREAD

**Issue by petr-buchin** [symfony/skeleton#16]
When I create a project using this skeleton, I don't see `config.yaml`, `config_dev.yaml` and other config files, familiar for Symfony Standard Edition users. So where should I put config values for bundles that are not "flex-compatible" yet?

**Comment by michalv8** [comment]
Example for [NelmioCorsBundle](https://github.com/nelmio/NelmioCorsBundle):
Config section for this bundle is named: `nelmio_cors` so you are just creating file: `config/nelmio_cors.yaml` and inside this file there is config only for this bundle:
```yaml
nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            ...
```
And configs for specific environments are in: `config/dev/nelmio_cors.yaml`, `config/prod/nelmio_cors.yaml` etc..
